### PR TITLE
Add favicon to server root as symlink

### PR DESCRIPTION
**Pull request by lfdebrux**
### What problem does this pull request solve?

Trello card: https://trello.com/c/j3LGb3mn/1375-blocked-on-tudor-crown-investigate-favicon-404-errors-in-production 

We're seeing a lot of `404`s in our server logs from clients trying to reach `/favicon.ico`. This PR hopefully will reduce those log messages by making it so we can serve the favicon from that path.

If poeople like this change I will roll it out the other apps.

I've tested this change in dev.

### Things to consider when reviewing

- Does it work when run on your machine?
- Is it clear what the code is doing?
- Do the commit messages explain why the changes were made?
- Are there all the unit tests needed?
- Has all relevant documentation been updated?

### CODE REVIEW

**Review by thomasiles — APPROVED** [review]
seems reasonable 👍

**Comment by chao-xian** [comment]
What about another approach to add it as a route, rather than a system symlink? What do you think?

**Comment by lfdebrux** [comment]
> What about another approach to add it as a route, rather than a system symlink? What do you think?

I looked into that, but I couldn't find a way to do it without introducing another request between the server and the client.

**Comment by chao-xian** [comment]
@lfdebrux can you change the commit message to title to add `... as symlink` as the PR description and message don't mention that, and GH only shows that it's a symlink when you view the file itself, not the diff. It'll be confusing for people in future.

**Review by chao-xian — APPROVED** [review]

**Pull request merged**
