### PR TITLE
Merge main-rails into main

### PR DESCRIPTION
**Pull request by jamie-o-wilkinson**
_**Prior to merging this PR, please ensure https://github.com/alphagov/forms-deploy/pull/292 is merged first**_

This seemingly quite enormous PR contains all of the changes merged into the `main-rails` branch, which has been used as a temporary alternative "main" branch for the migration of the product pages from a Middleman app on PaaS to a Rails app hosted on AWS infrastructure.

This means this PR contains the changes from all of the PRs merged into `main-rails`: https://github.com/alphagov/forms-product-page/pulls?q=is%3Apr+is%3Aclosed+base%3Amain-rails+is%3Amerged

The only as yet unreviewed commit is ~~the frustratingly named~~ [Initial deletion of existing product pages](https://github.com/alphagov/forms-product-page/pull/58/commits/b2ae33ae633367623c037ed4e9dc0ccc82236eee) as this was the initial commit on the `main-rails` branch.

### CODE REVIEW

**Review by cadmiumcat — APPROVED** [review]
I'm happy with this (based on all the experimenting we've done) but I think a review from another dev would be valuable

**Comment by chao-xian** [comment]
I think that as each of the 23 PRs(!) were reviewed by the other devs and I assume that this branch has been deployed and verified as working, then it's fine to merge.

My one tiny nit pick but not a blocker would be to rename the first commit message to remove the WIP prefix.

**Review by thomasiles — DISMISSED** [review]
Good work seeing this through to deployment 🥇

**Comment by jamie-o-wilkinson** [comment]
@chao-xian I know I'm super annoyed by the WIP commit too. @thomasiles and I discussed it yesterday. It is complicated by the fact we have merged commits from main into main-rails, and so editing the WIP commit will rewrite commits from main which feels wrong. 

We're gonna tidy it up now 😄

**Comment by chao-xian** [comment]
I agree redoing commits that are in main already is wrong. I'm confused how the current WIP one does that but I trust you and will leave you to it. Happy for it to be explained to me at some catch up in the future.

**Comment by jamie-o-wilkinson** [comment]
I have rebased onto main and edited the commits that added the privacy and accessibility pages to include their new content, and crucially, reworded the WIP commit!

This also clears up the merge commits from the PR process into `main-rails` so the history looks more linear.

**Review by cadmiumcat — APPROVED** [review]
I trust in your git-fu

**Review by lfdebrux — APPROVED** [review]
Changes look good to me 👍

**Review by chao-xian — APPROVED** [review]
Once we've checked this deploys ok I'm happy for this to be merged. Thank you for your hard work on this @jamie-o-wilkinson 👏

**Pull request merged**
